name: Latest blog post workflow

permissions:
  contents: write

on:
  schedule:
    # Runs every day
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "20"
          filter_comments: "" 
          commit_message: "Updated readme with the latest Medium data"
          remove_duplicates: true
          feed_list: "https://medium.com/feed/@jasonscchien"
          
  update_blogs:
    name: "Update Blogs"
    runs-on: ubuntu-latest
    steps:
      - name: "📥  Fetching Repository Contents"
        uses: actions/checkout@main

      - name: "📚  Hashnode Updater"
        uses: "varunsridharan/action-hashnode-blog@main"
        with:
          USERNAME: 'jason60810' # Hashnode Username
          BLOG_URL: 'https://jason60810.hashnode.dev/' # Blog URL
          COUNT: 10 # MAX Visisble
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  update-readme-with-codelove-blog:
    name: Update this repo's README with latest codelove blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "20"
          filter_comments: "" 
          commit_message: "Updated readme with the latest Medium data"
          remove_duplicates: true
          feed_list: "https://codelove.tw/api/posts?username=jason60810"   
  
  devcard:
    runs-on: ubuntu-latest
    steps:
      - name: devcard
        uses: dailydotdev/action-devcard@2.0.2
        with:
          devcard_id: ${{ secrets.DEVCARD_ID }}
