name: Latest blog post workflow

permissions:
  contents: write

on:
  schedule:
    # Runs every day
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches:
      - main # Replace with the branch you want to watch

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: '20'
          filter_comments: ''
          commit_message: 'Updated readme with the latest Medium data'
          remove_duplicates: true
          feed_list: 'https://medium.com/feed/@jasonscchien'

  update_blogs:
    name: Hashnode Latest Blogs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: HASHNODE_BLOG
          max_post_count: '10'
          commit_message: 'Updated readme with the latest Hashnode data'
          feed_list: 'https://jason60810.hashnode.dev/rss.xml'

  update_stats:
    name: Update GitHub stats cards
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate stats card
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: stats
          options: username=jaosn60810&show_icons=true&theme=radical
          path: stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_error: 'true'
      - name: Generate top languages card
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: top-langs
          options: username=jaosn60810&layout=compact
          path: top-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_error: 'true'
      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          add: 'stats.svg top-langs.svg'
          message: 'Update GitHub stats cards'

  codelove_blog:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: Updates Codelove Blog Outline
    steps:
      - uses: actions/checkout@v3
      - name: Updates Codelove Blog Outline
        uses: jaosn60810/readme-codelove-list@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CODELOVE_USERNAME: 'jason60810'
      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Update generated README'
  devcard:
    runs-on: ubuntu-latest
    steps:
      - name: devcard
        uses: dailydotdev/action-devcard@2.0.2
        with:
          devcard_id: ${{ secrets.DEVCARD_ID }}
