name: Latest blog post workflow

permissions:
  contents: write

on:
  schedule:
    # Runs every day
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches:
      - main # Replace with the branch you want to watch

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: '20'
          filter_comments: ''
          commit_message: 'Updated readme with the latest Medium data'
          remove_duplicates: true
          feed_list: 'https://medium.com/feed/@jasonscchien'

  update_blogs:
    name: 'Hashnode Latest Blogs'
    runs-on: ubuntu-latest
    steps:
      - name: 'Fetch Repository Contents'
        uses: actions/checkout@main

      - name: 'Hashnode Blog Action'
        uses: 'Sachin-chaurasiya/hashnode-blog-action@main'
        with:
          HASHNODE_PUBLICATION_NAME: 'jason60810.hashnode.dev'
          POST_COUNT: 10
          FORMAT: 'list'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  codelove_blog:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: Updates Codelove Blog Outline
    steps:
      - uses: actions/checkout@v3
      - name: Updates Codelove Blog Outline
        uses: jaosn60810/readme-codelove-list@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CODELOVE_USERNAME: 'jason60810'
          COMMITTER_USERNAME: 'jaosn60810'
          COMMITTER_EMAIL: 'jason60810@gmail.com'
          MAX_LINES: '8'
      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Update generated README'
  devcard:
    runs-on: ubuntu-latest
    steps:
      - name: devcard
        uses: dailydotdev/action-devcard@2.0.2
        with:
          devcard_id: ${{ secrets.DEVCARD_ID }}
