name: Latest blog post workflow
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "20"
          filter_comments: "" 
          commit_message: "Updated readme with the latest Medium data"
          remove_duplicates: true
          feed_list: "https://medium.com/feed/@jasonscchien"
